# -*- coding: utf-8 -*-
"""Strategic Competition Simulation Using Game Theory .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JyUyD6LDvHb5PETQgi7PBvS8C5uvH4mD
"""

import numpy as np
import matplotlib.pyplot as plt
from dataclasses import dataclass


# =========================================================
# MARKET PARAMETERS
# =========================================================

@dataclass
class MarketParameters:
    a: float = 100
    b: float = 1
    c1: float = 20
    c2: float = 20


# =========================================================
# COURNOT COMPETITION MODEL
# =========================================================

class CournotCompetition:

    def __init__(self, params: MarketParameters):
        self.params = params

    # -----------------------------------------------------
    # Market Price Function
    # -----------------------------------------------------
    def market_price(self, q1, q2):
        return self.params.a - self.params.b * (q1 + q2)

    # -----------------------------------------------------
    # Profit Function for Firm A
    # -----------------------------------------------------
    def profit_firm1(self, q1, q2):
        p = self.market_price(q1, q2)
        return (p - self.params.c1) * q1

    # -----------------------------------------------------
    # Profit Function for Firm B
    # -----------------------------------------------------
    def profit_firm2(self, q1, q2):
        p = self.market_price(q1, q2)
        return (p - self.params.c2) * q2

    # -----------------------------------------------------
    # Best Response Function for Firm A
    # -----------------------------------------------------
    def best_response_firm1(self, q2):

        return max(
            0,
            (self.params.a - self.params.c1 - self.params.b * q2)
            / (2 * self.params.b)
        )

    # -----------------------------------------------------
    # Best Response Function for Firm B
    # -----------------------------------------------------
    def best_response_firm2(self, q1):

        return max(
            0,
            (self.params.a - self.params.c2 - self.params.b * q1)
            / (2 * self.params.b)
        )

    # -----------------------------------------------------
    # Nash Equilibrium
    # -----------------------------------------------------
    def compute_nash_equilibrium(self):

        a = self.params.a
        b = self.params.b
        c1 = self.params.c1
        c2 = self.params.c2

        q1_star = (a - 2 * c1 + c2) / (3 * b)
        q2_star = (a - 2 * c2 + c1) / (3 * b)

        p_star = self.market_price(q1_star, q2_star)

        pi1 = self.profit_firm1(q1_star, q2_star)
        pi2 = self.profit_firm2(q1_star, q2_star)

        return {
            "q1": q1_star,
            "q2": q2_star,
            "price": p_star,
            "profit1": pi1,
            "profit2": pi2
        }

    # -----------------------------------------------------
    # Normal Form Representation
    # -----------------------------------------------------
    def generate_payoff_matrix(self, strategies):

        matrix = {}

        for q1 in strategies:

            matrix[q1] = {}

            for q2 in strategies:

                p1 = self.profit_firm1(q1, q2)
                p2 = self.profit_firm2(q1, q2)

                matrix[q1][q2] = (
                    round(p1, 2),
                    round(p2, 2)
                )

        return matrix

    # -----------------------------------------------------
    # Print Payoff Matrix
    # -----------------------------------------------------
    def print_payoff_matrix(self, strategies):

        matrix = self.generate_payoff_matrix(strategies)

        print("\n========== NORMAL FORM PAYOFF MATRIX ==========")

        for q1 in matrix:

            print(f"\nFirm A Quantity = {q1}")

            for q2 in matrix[q1]:

                print(
                    f"Firm B Quantity = {q2}"
                    f" --> Payoffs {matrix[q1][q2]}"
                )

    # -----------------------------------------------------
    # Dominated Strategies for Firm A
    # -----------------------------------------------------
    def dominated_strategies_firm1(self, strategies):

        dominated = []

        for s1 in strategies:

            for s2 in strategies:

                if s1 == s2:
                    continue

                dominated_flag = True

                for opponent in strategies:

                    payoff1 = self.profit_firm1(s1, opponent)
                    payoff2 = self.profit_firm1(s2, opponent)

                    if payoff1 >= payoff2:
                        dominated_flag = False
                        break

                if dominated_flag:
                    dominated.append((s1, s2))

        return dominated

    # -----------------------------------------------------
    # Dominated Strategies for Firm B
    # -----------------------------------------------------
    def dominated_strategies_firm2(self, strategies):

        dominated = []

        for s1 in strategies:

            for s2 in strategies:

                if s1 == s2:
                    continue

                dominated_flag = True

                for opponent in strategies:

                    payoff1 = self.profit_firm2(opponent, s1)
                    payoff2 = self.profit_firm2(opponent, s2)

                    if payoff1 >= payoff2:
                        dominated_flag = False
                        break

                if dominated_flag:
                    dominated.append((s1, s2))

        return dominated

    # -----------------------------------------------------
    # Plot Best Response Curves
    # -----------------------------------------------------
    def plot_best_response_curves(self):

        q_values = np.linspace(0, 100, 300)

        br1 = [
            self.best_response_firm1(q)
            for q in q_values
        ]

        br2 = [
            self.best_response_firm2(q)
            for q in q_values
        ]

        equilibrium = self.compute_nash_equilibrium()

        plt.figure(figsize=(10, 7))

        plt.plot(
            q_values,
            br1,
            linewidth=2,
            label="Firm A Best Response"
        )

        plt.plot(
            br2,
            q_values,
            linewidth=2,
            label="Firm B Best Response"
        )

        plt.scatter(
            equilibrium["q2"],
            equilibrium["q1"],
            s=150,
            label="Nash Equilibrium"
        )

        plt.xlabel("Firm B Quantity")
        plt.ylabel("Firm A Quantity")

        plt.title(
            "Best Response Curves and Nash Equilibrium"
        )

        plt.legend()
        plt.grid(True)

        plt.savefig("best_response_curves.png")

        plt.show()

    # -----------------------------------------------------
    # Plot Profit vs Strategy
    # -----------------------------------------------------
    def plot_profit_vs_strategy(self):

        q = np.linspace(0, 80, 300)

        fixed_q2 = 20

        profits = [
            self.profit_firm1(x, fixed_q2)
            for x in q
        ]

        plt.figure(figsize=(10, 7))

        plt.plot(
            q,
            profits,
            linewidth=2
        )

        plt.xlabel("Firm A Quantity")
        plt.ylabel("Profit")

        plt.title(
            "Profit vs Strategy for Firm A"
        )

        plt.grid(True)

        plt.savefig("profit_vs_strategy.png")

        plt.show()

    # -----------------------------------------------------
    # Plot Profit Surface
    # -----------------------------------------------------
    def plot_profit_surface(self):

        q1 = np.linspace(0, 80, 100)
        q2 = np.linspace(0, 80, 100)

        profits = []

        for x in q1:

            row = []

            for y in q2:

                row.append(
                    self.profit_firm1(x, y)
                )

            profits.append(row)

        profits = np.array(profits)

        plt.figure(figsize=(10, 7))

        contour = plt.contourf(
            q2,
            q1,
            profits,
            levels=20
        )

        plt.colorbar(contour)

        plt.xlabel("Firm B Quantity")
        plt.ylabel("Firm A Quantity")

        plt.title(
            "Profit Surface for Firm A"
        )

        plt.savefig("profit_surface.png")

        plt.show()


# =========================================================
# EXTENSIVE FORM GAME
# =========================================================

class ExtensiveFormGame:

    def __init__(self, game):
        self.game = game

    # -----------------------------------------------------
    # Tree Structure Representation
    # -----------------------------------------------------
    def build_game_tree(self):

        tree = {
            "Firm A": {
                "Low Quantity": {
                    "Firm B": [
                        "Low",
                        "Medium",
                        "High"
                    ]
                },

                "Medium Quantity": {
                    "Firm B": [
                        "Low",
                        "Medium",
                        "High"
                    ]
                },

                "High Quantity": {
                    "Firm B": [
                        "Low",
                        "Medium",
                        "High"
                    ]
                }
            }
        }

        return tree

    # -----------------------------------------------------
    # Print Tree Structure
    # -----------------------------------------------------
    def print_game_tree(self):

        tree = self.build_game_tree()

        print(
            "\n========== EXTENSIVE FORM TREE =========="
        )

        for action in tree["Firm A"]:

            print(f"\nFirm A chooses: {action}")

            responses = tree["Firm A"][action]["Firm B"]

            for response in responses:
                print(f"   -> Firm B responds: {response}")

    # -----------------------------------------------------
    # Draw Game Tree
    # -----------------------------------------------------
    def draw_game_tree(self):

        plt.figure(figsize=(12, 7))

        plt.text(0.5, 0.9, "Firm A", ha='center', fontsize=14)

        plt.plot([0.5, 0.2], [0.85, 0.65])
        plt.plot([0.5, 0.5], [0.85, 0.65])
        plt.plot([0.5, 0.8], [0.85, 0.65])

        plt.text(0.2, 0.62, "Low", ha='center')
        plt.text(0.5, 0.62, "Medium", ha='center')
        plt.text(0.8, 0.62, "High", ha='center')

        plt.plot([0.2, 0.1], [0.58, 0.4])
        plt.plot([0.2, 0.2], [0.58, 0.4])
        plt.plot([0.2, 0.3], [0.58, 0.4])

        plt.plot([0.5, 0.4], [0.58, 0.4])
        plt.plot([0.5, 0.5], [0.58, 0.4])
        plt.plot([0.5, 0.6], [0.58, 0.4])

        plt.plot([0.8, 0.7], [0.58, 0.4])
        plt.plot([0.8, 0.8], [0.58, 0.4])
        plt.plot([0.8, 0.9], [0.58, 0.4])

        positions = [
            (0.1, "Low"),
            (0.2, "Medium"),
            (0.3, "High"),
            (0.4, "Low"),
            (0.5, "Medium"),
            (0.6, "High"),
            (0.7, "Low"),
            (0.8, "Medium"),
            (0.9, "High")
        ]

        for x, label in positions:
            plt.text(x, 0.35, label, ha='center')

        plt.title("Extensive Form Game Tree")

        plt.axis('off')

        plt.savefig("extensive_form_tree.png")

        plt.show()

    # -----------------------------------------------------
    # Stackelberg Equilibrium
    # -----------------------------------------------------
    def stackelberg_equilibrium(self):

        a = self.game.params.a
        b = self.game.params.b
        c1 = self.game.params.c1
        c2 = self.game.params.c2

        q1 = (a - 2 * c1 + c2) / (2 * b)

        q2 = self.game.best_response_firm2(q1)

        price = self.game.market_price(q1, q2)

        profit1 = self.game.profit_firm1(q1, q2)
        profit2 = self.game.profit_firm2(q1, q2)

        return {
            "leader_quantity": q1,
            "follower_quantity": q2,
            "price": price,
            "leader_profit": profit1,
            "follower_profit": profit2
        }


# =========================================================
# SIMULATION MANAGER
# =========================================================

class SimulationManager:

    def run_all_scenarios(self):

        scenarios = [

            {
                "name": "Base Scenario",

                "params": MarketParameters(
                    a=100,
                    b=1,
                    c1=20,
                    c2=20
                )
            },

            {
                "name": "High Cost for Firm A",

                "params": MarketParameters(
                    a=100,
                    b=1,
                    c1=35,
                    c2=20
                )
            },

            {
                "name": "Demand Increase",

                "params": MarketParameters(
                    a=140,
                    b=1,
                    c1=20,
                    c2=20
                )
            },

            {
                "name": "Demand Decrease",

                "params": MarketParameters(
                    a=70,
                    b=1,
                    c1=20,
                    c2=20
                )
            },

            {
                "name": "Cost Increase for Both Firms",

                "params": MarketParameters(
                    a=100,
                    b=1,
                    c1=40,
                    c2=40
                )
            },

            {
                "name": "High Market Price Sensitivity",

                "params": MarketParameters(
                    a=120,
                    b=0.5,
                    c1=20,
                    c2=20
                )
            }
        ]

        print(
            "\n========== MULTIPLE SIMULATIONS =========="
        )

        for scenario in scenarios:

            print("\n====================================")
            print(f"Scenario: {scenario['name']}")
            print("====================================")

            game = CournotCompetition(
                scenario["params"]
            )

            equilibrium = (
                game.compute_nash_equilibrium()
            )

            print(
                f"Firm A Quantity : "
                f"{equilibrium['q1']:.2f}"
            )

            print(
                f"Firm B Quantity : "
                f"{equilibrium['q2']:.2f}"
            )

            print(
                f"Market Price : "
                f"{equilibrium['price']:.2f}"
            )

            print(
                f"Firm A Profit : "
                f"{equilibrium['profit1']:.2f}"
            )

            print(
                f"Firm B Profit : "
                f"{equilibrium['profit2']:.2f}"
            )


# =========================================================
# DISPLAY FUNCTIONS
# =========================================================

def display_best_response_functions():

    print(
        "\n========== BEST RESPONSE FUNCTIONS =========="
    )

    print(
        "BR1(q2) = (a - c1 - b*q2) / (2b)"
    )

    print(
        "BR2(q1) = (a - c2 - b*q1) / (2b)"
    )


def display_nash_equilibrium(game):

    equilibrium = (
        game.compute_nash_equilibrium()
    )

    print(
        "\n========== NASH EQUILIBRIUM =========="
    )

    print(
        f"Firm A Quantity : "
        f"{equilibrium['q1']:.2f}"
    )

    print(
        f"Firm B Quantity : "
        f"{equilibrium['q2']:.2f}"
    )

    print(
        f"Market Price : "
        f"{equilibrium['price']:.2f}"
    )

    print(
        f"Firm A Profit : "
        f"{equilibrium['profit1']:.2f}"
    )

    print(
        f"Firm B Profit : "
        f"{equilibrium['profit2']:.2f}"
    )


def display_dominated_strategies(
        game,
        strategies
):

    print(
        "\n========== DOMINATED STRATEGIES =========="
    )

    dominated_firm1 = (
        game.dominated_strategies_firm1(
            strategies
        )
    )

    dominated_firm2 = (
        game.dominated_strategies_firm2(
            strategies
        )
    )

    print("\nFirm A:")

    if len(dominated_firm1) == 0:
        print("No dominated strategies")

    else:

        for strategy in dominated_firm1:

            print(
                f"{strategy[0]} dominated by "
                f"{strategy[1]}"
            )

    print("\nFirm B:")

    if len(dominated_firm2) == 0:
        print("No dominated strategies")

    else:

        for strategy in dominated_firm2:

            print(
                f"{strategy[0]} dominated by "
                f"{strategy[1]}"
            )


def display_stackelberg(game):

    extensive = ExtensiveFormGame(game)

    extensive.print_game_tree()

    extensive.draw_game_tree()

    result = extensive.stackelberg_equilibrium()

    print(
        "\n========== STACKELBERG EQUILIBRIUM =========="
    )

    print(
        f"Leader Quantity : "
        f"{result['leader_quantity']:.2f}"
    )

    print(
        f"Follower Quantity : "
        f"{result['follower_quantity']:.2f}"
    )

    print(
        f"Market Price : "
        f"{result['price']:.2f}"
    )

    print(
        f"Leader Profit : "
        f"{result['leader_profit']:.2f}"
    )

    print(
        f"Follower Profit : "
        f"{result['follower_profit']:.2f}"
    )


# =========================================================
# MAIN PROGRAM
# =========================================================

def main():

    print(
        "\n=========================================="
    )

    print(
        "STRATEGIC COMPETITION SIMULATION PROJECT"
    )

    print(
        "=========================================="
    )

    parameters = MarketParameters(
        a=100,
        b=1,
        c1=20,
        c2=20
    )

    game = CournotCompetition(parameters)

    display_best_response_functions()

    display_nash_equilibrium(game)

    strategies = [10, 20, 30, 40]

    game.print_payoff_matrix(strategies)

    display_dominated_strategies(
        game,
        strategies
    )

    display_stackelberg(game)

    simulation = SimulationManager()

    simulation.run_all_scenarios()

    game.plot_best_response_curves()

    game.plot_profit_vs_strategy()

    game.plot_profit_surface()


# =========================================================
# RUN PROGRAM
# =========================================================

if __name__ == "__main__":
    main()